table almacen

	column almacen
		dataType: string
		summarizeBy: none
		sourceColumn: almacen

		annotation SummarizationSetBy = Automatic

	column direccion
		dataType: string
		summarizeBy: none
		sourceColumn: direccion

		annotation SummarizationSetBy = Automatic

	column responsable
		dataType: string
		summarizeBy: none
		sourceColumn: responsable

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column id_almacen = almacen[almacen] & almacen[source]
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition almacen = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    almacen_Sheet = Origen{[Item="almacen",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(almacen_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"almacen", type text}, {"direccion", type text}, {"responsable", type text}, {"source", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

