table amortizacion

	column AMORTIZACION_ID
		dataType: int64
		formatString: 0
		summarizeBy: count
		sourceColumn: AMORTIZACION_ID

		annotation SummarizationSetBy = Automatic

	column DESCRIPCION
		dataType: string
		summarizeBy: none
		sourceColumn: DESCRIPCION

		annotation SummarizationSetBy = Automatic

	column INSUMO
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: INSUMO

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	partition amortizacion = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    amortizacion_Sheet = Origen{[Item="amortizacion",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(amortizacion_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"AMORTIZACION_ID", Int64.Type}, {"DESCRIPCION", type text}, {"INSUMO", Int64.Type}, {"source", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

