table amortizacion_contratista

	column OBRA
		dataType: string
		summarizeBy: none
		sourceColumn: OBRA

		annotation SummarizationSetBy = Automatic

	column AMORTIZACION_ID
		dataType: int64
		formatString: 0
		summarizeBy: count
		sourceColumn: AMORTIZACION_ID

		annotation SummarizationSetBy = Automatic

	column NUMPRO
		dataType: string
		summarizeBy: none
		sourceColumn: NUMPRO

		annotation SummarizationSetBy = Automatic

	column CLAVE_AMORT
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: CLAVE_AMORT

		annotation SummarizationSetBy = Automatic

	column CANTIDAD
		dataType: int64
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum
		sourceColumn: CANTIDAD

		annotation SummarizationSetBy = Automatic

	column id_convenio
		dataType: string
		summarizeBy: none
		sourceColumn: id_convenio

		annotation SummarizationSetBy = Automatic

	column id_retencion_compras
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: id_retencion_compras

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column id_cc
		dataType: string
		summarizeBy: none
		sourceColumn: id_cc

		annotation SummarizationSetBy = Automatic

	column prov_id
		dataType: string
		summarizeBy: none
		sourceColumn: prov_id

		annotation SummarizationSetBy = Automatic

	column prov_id_cc
		dataType: string
		summarizeBy: none
		sourceColumn: prov_id_cc

		annotation SummarizationSetBy = Automatic

	column 'Convenio ID' = amortizacion_contratista[id_convenio] & amortizacion_contratista[prov_id_cc]
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ESTIMACION_ID
		dataType: string
		summarizeBy: none
		sourceColumn: ESTIMACION_ID

		annotation SummarizationSetBy = Automatic

	column Amortizacion = IF(ISBLANK(amortizacion_contratista[CANTIDAD]), 0, amortizacion_contratista[CANTIDAD])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column LIMITE
		dataType: double
		summarizeBy: sum
		sourceColumn: LIMITE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column porcentaje_amortizacion
		dataType: double
		summarizeBy: sum
		sourceColumn: porcentaje_amortizacion

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Anticipo Obra' = ```
			
			VAR anticipo = 
			--  && amortizacion_contratista[CLAVE_AMORT] = 1
			IF(amortizacion_contratista[AMORTIZACION_ID] = 1, amortizacion_contratista[LIMITE])
			RETURN
			IF(ISBLANK(anticipo), 0, anticipo)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Fondo Garantía Limite' =
			
			--  && amortizacion_contratista[CLAVE_AMORT] = 2
			VAR fon_gar = IF(amortizacion_contratista[AMORTIZACION_ID] = 2, amortizacion_contratista[LIMITE])
			RETURN
			IF(ISBLANK(fon_gar), 0, fon_gar)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Dispersion Nomina' =
			
			--  && amortizacion_contratista[CLAVE_AMORT] IN {3,2}
			VAR disp_nom = IF(amortizacion_contratista[AMORTIZACION_ID] = 3, amortizacion_contratista[LIMITE])
			RETURN
			IF(ISBLANK(disp_nom), 0, disp_nom)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ISR =
			
			--  && amortizacion_contratista[CLAVE_AMORT] = 4
			VAR isr = IF(amortizacion_contratista[AMORTIZACION_ID] = 4, amortizacion_contratista[LIMITE])
			RETURN
			IF(ISBLANK(isr), 0, isr)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Porc Anticipo Obra' =
			
			--  && amortizacion_contratista[CLAVE_AMORT] = 1
			VAR porcentaje = IF(amortizacion_contratista[AMORTIZACION_ID] = 1, amortizacion_contratista[porcentaje_amortizacion], 0)
			RETURN
			porcentaje/100
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Porc Fondo Garantia' =
			
			--  && amortizacion_contratista[CLAVE_AMORT] = 2
			VAR porcentaje = IF(amortizacion_contratista[AMORTIZACION_ID] = 2, amortizacion_contratista[porcentaje_amortizacion], 0)
			RETURN
			porcentaje/100
		formatString: 0.00%;-0.00%;0.00%
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje Dispercón Nómina' =
			
			--  && amortizacion_contratista[CLAVE_AMORT] = 3
			VAR porcentaje = IF(amortizacion_contratista[AMORTIZACION_ID] = 3, amortizacion_contratista[porcentaje_amortizacion], 0)
			RETURN
			porcentaje/100
		formatString: 0.00%;-0.00%;0.00%
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Porcentaje ISR' =
			
			--  && amortizacion_contratista[CLAVE_AMORT] = 4
			VAR porcentaje = IF(amortizacion_contratista[AMORTIZACION_ID] = 4, amortizacion_contratista[porcentaje_amortizacion], 0)
			RETURN
			porcentaje/100
		formatString: 0.00%;-0.00%;0.00%
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Garantías IMSS' = ```
			
			VAR anticipo = 
			IF(amortizacion_contratista[AMORTIZACION_ID] = 3 && amortizacion_contratista[CLAVE_AMORT] = 1, amortizacion_contratista[LIMITE])
			RETURN
			IF(ISBLANK(anticipo), 0, anticipo)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Porc Garantía IMSS' =
			
			VAR porcentaje = IF(amortizacion_contratista[AMORTIZACION_ID] = 3 && amortizacion_contratista[CLAVE_AMORT] = 1, amortizacion_contratista[porcentaje_amortizacion], 0)
			RETURN
			porcentaje/100
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition amortizacion_contratista = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    amortizacion_contratista_Sheet = Origen{[Item="amortizacion_contratista",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(amortizacion_contratista_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"OBRA", type text}, {"AMORTIZACION_ID", Int64.Type}, {"NUMPRO", type text}, {"CLAVE_AMORT", Int64.Type}, {"CANTIDAD", Int64.Type}, {"id_convenio", type text}, {"id_retencion_compras", Int64.Type}, {"source", type text}, {"id_cc", type text}, {"prov_id", type text}, {"prov_id_cc", type text}, {"LIMITE", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

