table empleados_autorizo

	column empleado
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: empleado

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column puesto
		dataType: string
		summarizeBy: none
		sourceColumn: puesto

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column id_empleado = empleados_autorizo[empleado] & empleados_autorizo[source]
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column id_puesto = empleados_autorizo[puesto] & empleados_autorizo[source]
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition empleados_autorizo = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    empleados_Sheet = Origen{[Item="empleados",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(empleados_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"empleado", Int64.Type}, {"descripcion", type text}, {"source", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

