table empresas

	column id_empresa
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: id_empresa

		annotation SummarizationSetBy = Automatic

	column nombre_empresa
		dataType: string
		summarizeBy: none
		sourceColumn: nombre_empresa

		annotation SummarizationSetBy = Automatic

	column direccion
		dataType: string
		summarizeBy: none
		sourceColumn: direccion

		annotation SummarizationSetBy = Automatic

	column rfc
		dataType: string
		summarizeBy: none
		sourceColumn: rfc

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column Empresa = empresas[id_empresa] & " " & empresas[nombre_empresa]
		summarizeBy: none
		sortByColumn: id_empresa

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Columna de Prueba' = 0
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition empresas = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    empresas_Sheet = Origen{[Item="empresas",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(empresas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_empresa", Int64.Type}, {"nombre_empresa", type text}, {"direccion", type text}, {"rfc", type text}, {"source", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

