table insumos

	column insumo
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: insumo

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column id_insumo = insumos[insumo] & insumos[source]
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition insumos = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    insumos_Sheet = Origen{[Item="insumos",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(insumos_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"insumo", Int64.Type}, {"descripcion", type text}, {"source", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

