table libre_abordo

	column numero
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: numero

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	partition libre_abordo = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    libre_abordo_Sheet = Origen{[Item="libre_abordo",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(libre_abordo_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"numero", Int64.Type}, {"descripcion", type text}, {"source", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

