table partidas

	column OBRA
		dataType: string
		summarizeBy: none
		sourceColumn: OBRA

		annotation SummarizationSetBy = Automatic

	column PARTIDA
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: PARTIDA

		annotation SummarizationSetBy = Automatic

	column DS_PARTIDA
		dataType: string
		summarizeBy: none
		sourceColumn: DS_PARTIDA

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column id_cc = partidas[OBRA] & partidas[source]
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition partidas = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    partidas_Sheet = Origen{[Item="partidas",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(partidas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"OBRA", type text}, {"PARTIDA", Int64.Type}, {"DS_PARTIDA", type text}, {"source", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

