table presupuesto_actualizado

	column obra
		dataType: string
		summarizeBy: none
		sourceColumn: obra

		annotation SummarizationSetBy = Automatic

	column tipo_explosion
		dataType: string
		summarizeBy: none
		sourceColumn: tipo_explosion

		annotation SummarizationSetBy = Automatic

	column precio
		dataType: double
		summarizeBy: sum
		sourceColumn: precio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column importe
		dataType: double
		summarizeBy: sum
		sourceColumn: importe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cantidad_aditiva
		dataType: double
		summarizeBy: sum
		sourceColumn: cantidad_aditiva

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cantidad_deductiva
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: cantidad_deductiva

		annotation SummarizationSetBy = Automatic

	column cantidad_extra
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: cantidad_extra

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column id_obra
		dataType: string
		summarizeBy: none
		sourceColumn: id_obra

		annotation SummarizationSetBy = Automatic

	column total_aditiva
		dataType: double
		summarizeBy: sum
		sourceColumn: total_aditiva

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_deductiva
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: total_deductiva

		annotation SummarizationSetBy = Automatic

	column total_extra
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: total_extra

		annotation SummarizationSetBy = Automatic

	column presupuesto_liberado_inicial
		dataType: double
		summarizeBy: sum
		sourceColumn: presupuesto_liberado_inicial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition presupuesto_actualizado = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\proforma_data.xlsx"), null, true),
				    presupuesto_actualizado_Sheet = Origen{[Item="presupuesto_actualizado",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(presupuesto_actualizado_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"obra", type text}, {"tipo_explosion", type text}, {"precio", type number}, {"importe", type number}, {"cantidad_aditiva", type number}, {"cantidad_deductiva", Int64.Type}, {"cantidad_extra", Int64.Type}, {"source", type text}, {"id_obra", type text}, {"total_aditiva", type number}, {"total_deductiva", Int64.Type}, {"total_extra", Int64.Type}, {"presupuesto_liberado_inicial", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

