table puestos_autorizo

	column puesto
		dataType: string
		summarizeBy: none
		sourceColumn: puesto

		annotation SummarizationSetBy = Automatic

	column descripcion
		dataType: string
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column id_puesto = puestos_autorizo[puesto] & puestos_autorizo[source]
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition puestos_autorizo = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    puestos_Sheet = Origen{[Item="puestos",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(puestos_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"puesto", type text}, {"descripcion", type text}, {"source", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

