table tipos_centro

	column tipo_centro
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: tipo_centro

		annotation SummarizationSetBy = Automatic

	column descripcion_tipo_centro
		dataType: string
		summarizeBy: none
		sourceColumn: descripcion_tipo_centro

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column id_tc
		dataType: string
		summarizeBy: none
		sourceColumn: id_tc

		annotation SummarizationSetBy = Automatic

	column 'numero nombre tipo centro' = tipos_centro[tipo_centro] & " " & tipos_centro[descripcion_tipo_centro]
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition tipos_centro = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\control_obra_data.xlsx"), null, true),
				    tipos_centro_Sheet = Origen{[Item="tipos_centro",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(tipos_centro_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"tipo_centro", Int64.Type}, {"descripcion_tipo_centro", type text}, {"source", type text}, {"id_tc", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

