table ventas

	column ID
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Desarrollo.Nombre'
		dataType: string
		summarizeBy: none
		sourceColumn: Desarrollo.Nombre

		annotation SummarizationSetBy = Automatic

	column 'Agente.Nombre'
		dataType: string
		summarizeBy: none
		sourceColumn: Agente.Nombre

		annotation SummarizationSetBy = Automatic

	column 'Agente.Apellidos'
		dataType: string
		summarizeBy: none
		sourceColumn: Agente.Apellidos

		annotation SummarizationSetBy = Automatic

	column 'EstatusVenta.Nombre'
		dataType: string
		summarizeBy: none
		sourceColumn: EstatusVenta.Nombre

		annotation SummarizationSetBy = Automatic

	column Importe
		dataType: double
		summarizeBy: sum
		sourceColumn: Importe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IdExpediente
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: IdExpediente

		annotation SummarizationSetBy = Automatic

	column ImporteLetra
		dataType: string
		summarizeBy: none
		sourceColumn: ImporteLetra

		annotation SummarizationSetBy = Automatic

	column IdCliente
		dataType: string
		summarizeBy: none
		sourceColumn: IdCliente

		annotation SummarizationSetBy = Automatic

	column 'Desarrollo.ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Desarrollo.ID

		annotation SummarizationSetBy = Automatic

	column 'Desarrollo.IdCompania'
		dataType: string
		summarizeBy: none
		sourceColumn: Desarrollo.IdCompania

		annotation SummarizationSetBy = Automatic

	column 'Desarrollo.Compania.Clave'
		dataType: string
		summarizeBy: none
		sourceColumn: Desarrollo.Compania.Clave

		annotation SummarizationSetBy = Automatic

	column 'Expediente.ClaveLegacy'
		dataType: string
		summarizeBy: none
		sourceColumn: Expediente.ClaveLegacy

		annotation SummarizationSetBy = Automatic

	partition ventas = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\REPORTES_CORPORATIVO_PBI\outputs\ingresos_data.xlsx"), null, true),
				    ventas_Sheet = Origen{[Item="ventas",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(ventas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID", Int64.Type}, {"Desarrollo.Nombre", type text}, {"Agente.Nombre", type text}, {"Agente.Apellidos", type text}, {"EstatusVenta.Nombre", type text}, {"Importe", type number}, {"IdExpediente", Int64.Type}, {"ImporteLetra", type text}}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Tipo cambiado",{"ID", "IdCliente", "Desarrollo.ID", "Desarrollo.Nombre", "Desarrollo.IdCompania", "Desarrollo.Compania.Clave", "Agente.Nombre", "Agente.Apellidos", "EstatusVenta.Nombre", "Importe", "IdExpediente", "Expediente.ClaveLegacy", "ImporteLetra"})
				in
				    #"Otras columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

